// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozlomikwnqerjjomdzdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96bG9taWt3bnFlcmpqb21kemRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzQ5NjgsImV4cCI6MjA3MzExMDk2OH0.Ly8pboHsamiuvnp5izBpDqzWXOEmgjWgHkItOJF2pxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});